# Generated by Django 4.0.6 on 2022-08-03 14:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('location', tinymce.models.HTMLField(verbose_name='Место проведения')),
                ('moment_from', models.DateTimeField(verbose_name='Дата и время начала')),
                ('moment_to', models.DateTimeField(verbose_name='Дата и время окончания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Телеграм ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, verbose_name='Эл. почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Контактный телефон')),
                ('company', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, default='', upload_to='', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='MeetupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, verbose_name='Событие')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание события')),
                ('type', models.CharField(choices=[('primary', 'Основное'), ('secondary', 'Вспомогательное')], default='primary', max_length=10, verbose_name='Тип события')),
                ('moment_from', models.DateTimeField(verbose_name='Время начала')),
                ('moment_to', models.DateTimeField(verbose_name='Время окончания')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup', to='event.meetup', verbose_name='Мероприятие')),
                ('speakers', models.ManyToManyField(blank=True, related_name='event_speakers', to='event.participant', verbose_name='Докладчики')),
            ],
            options={
                'verbose_name': 'Детали мероприятия',
                'verbose_name_plural': 'Детали мероприятия',
            },
        ),
    ]
