# Generated by Django 4.0.6 on 2022-08-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetupdetail',
            options={'verbose_name': 'Событие мероприятия', 'verbose_name_plural': 'События мероприятий'},
        ),
        migrations.RemoveField(
            model_name='meetupdetail',
            name='speakers',
        ),
        migrations.AlterField(
            model_name='meetupdetail',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.meetup', verbose_name='Мероприятие'),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('listener', 'Слушатель'), ('speaker', 'Докладчик')], db_index=True, max_length=10, verbose_name='Статус участника')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.meetupdetail', verbose_name='Событие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.participant', verbose_name='Участник события')),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники событий',
            },
        ),
    ]
