# Generated by Django 4.0.6 on 2022-08-04 08:54

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_meetupdetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание события')),
                ('type', models.CharField(choices=[('primary', 'Основное'), ('secondary', 'Вспомогательное')], default='primary', max_length=10, verbose_name='Тип события')),
                ('moment_from', models.DateTimeField(verbose_name='Время начала')),
                ('moment_to', models.DateTimeField(verbose_name='Время окончания')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.meetup', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Событие мероприятия',
                'verbose_name_plural': 'События мероприятий',
            },
        ),
        migrations.RemoveField(
            model_name='meetupdetail',
            name='meetup',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
        migrations.DeleteModel(
            name='MeetupDetail',
        ),
    ]
