# Generated by Django 4.0.6 on 2022-08-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_remove_meetupdetail_meetup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('listener', 'Слушатель'), ('speaker', 'Докладчик')], db_index=True, max_length=10, verbose_name='Статус участника')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.event', verbose_name='Событие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.participant', verbose_name='Участник события')),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники событий',
            },
        ),
    ]
