# Generated by Django 4.0.6 on 2022-08-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='где надо', max_length=255, verbose_name='Место прохождения'),
            preserve_default=False,
        ),
    ]
