# Generated by Django 4.0.6 on 2022-08-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
