# Generated by Django 4.0.6 on 2022-08-04 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_notification_addressee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pos_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очерёдность событий'),
        ),
    ]
