# Generated by Django 4.0.6 on 2022-08-05 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_pos_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pos_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый №'),
        ),
    ]
