# Generated by Django 4.0.6 on 2022-08-05 12:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_pos_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, verbose_name='Место прохождения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='moment_from',
            field=models.DateTimeField(blank=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='moment_to',
            field=models.DateTimeField(blank=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='moment_from',
            field=models.DateTimeField(blank=True, verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='moment_to',
            field=models.DateTimeField(blank=True, verbose_name='Дата и время окончания'),
        ),
    ]
