# Generated by Django 4.0.6 on 2022-08-06 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_event_description_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='moment',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 6, 14, 12, 23, 952606), verbose_name='Дата и время создания вопроса'),
            preserve_default=False,
        ),
    ]
