# Generated by Django 4.0.6 on 2022-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_question_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked',
            field=models.BooleanField(default=False, verbose_name='Вопрос отвечен'),
        ),
    ]
