# Generated by Django 4.0.6 on 2022-08-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_question_asked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='asked',
            new_name='answered',
        ),
    ]
